language: c
before_install:
  - sudo apt-get update -qq
  - cd travis-install
  - sudo bash install.sh -qq
  - cd Ubuntu
  - sudo bash opencv_latest.sh -qq
  - cd ..
  - cd ..
install:
script:
  - make
after_script:
  - cd bin
  - ./main --init-only